name: Build and Deploy Go App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Initialize Go module
        run: |
          go mod init github.com/nor5/cowsay-app
          go mod tidy

      - name: Build the Go app
        run: |
          go build -o myapp main.go

      - name: Build Docker image
        run: |
          docker build -t nor5/cowsay-app:latest .

      - name: Push Docker image to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          docker push nor5/cowsay-app:latest
